---
title: "2015 US Poverity Rates by County"
author: "Stephanie Denis"
date: "6/20/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, comment="")
```

* * * 

# Load Libraries
```{r load-libraries}
# Load packages
library(xlsx); library(ggplot2); library(reshape); library(reshape2); 
library(tidyr); library(plyr); library(dplyr)
```

* * * 

# Load Data
```{r load-data}
# Set working directory
setwd("~/Desktop/Rprogramming/9_Developing_Data_Products/poverty/counties")

# Load poverty data from Census
library("readxl")
data <- read_excel("est15ALL.xls", sheet = "est15ALL")

# Load state names
states <- read.xlsx("states.xlsx", sheetIndex=1)
```

* * *

# Clean Data
```{r clean-data}
# Remove unnecessary rows and columns
df <- data[-c(1:3), -c(5,11,17,6:7,9:10,12:13,15:16,18:19,21:22,24:31)] 

# Rename columns
names(df)[1] <- "state_fips" 
names(df)[2] <- "county_fips"   
names(df)[3] <- "postal_code"   
names(df)[4] <- "names"
names(df)[5] <- "All"
names(df)[6] <- "x0_17"
names(df)[7] <- "x5_17"
names(df)[8] <- "med.inc"

# Convert from character class to factor
sapply(df, class)
df$postal_code <- as.factor(df$postal_code)
df$names <- as.factor(df$names)

# Convert from character class to numeric
library(taRifx)
df <- japply(df, which(sapply(df, class)=="character"), as.numeric)
sapply(df, class)

# Merge state names
df2 <- merge(df, states, by = "postal_code", incomparables = NA)

# Remove US
df2 <- subset(df2, State!=0)

# Convert factor levels to lowercase
levels(df2$names) <- tolower(levels(df2$names))
levels(df2$state) <- tolower(levels(df2$state))

# Remove "city and borough, county, borough, census area, parish, 's county" from names
df2$namesclean <- df2$names
df2$namesclean <- gsub("city and borough", "", df2$namesclean)
df2$namesclean <- gsub(" county", "", df2$namesclean)
df2$namesclean <- gsub(" borough", "", df2$namesclean)
df2$namesclean <- gsub(" census area", "", df2$namesclean)
df2$namesclean <- gsub(" parish", "", df2$namesclean)
df2$namesclean <- gsub("'s", "s", df2$namesclean)

# Combine state and namesclean
df2$name <- paste(df2$state, df2$namesclean, sep=",")

# Rename DC
levels(df2$state)[levels(df2$state)=="dist. of columbia"] <- "district of columbia, washington"

# Remove AK, DC, HI
df3 <- subset(df2, postal_code != "AK" & postal_code != "DC" & postal_code != "HI")

# Poverty data
poverty2015 <-  subset(df3, select = c(name, All))
names(poverty2015)[2] <- "POV15"

# Remove missing values
poverty2015 <- na.omit(poverty2015)

# Save file
save(poverty2015, file="POV15.Rda")

```

* * *

# Print Map
```{r print-map}
# Load libraries
library(maps)
library(mapproj)

# Print map
source("~/Desktop/Rprogramming/ShinyApps/census-app/helpers.R")
percent_map(poverty2015$POV15, "blue", "% All ages")
```

